# Generated by Django 4.2.5 on 2023-10-04 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import intent.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agent", "0014_remove_entitytypes_agent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("displayName", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True, null=True, verbose_name="Event description")),
                ("trigger_condition", models.TextField(blank=True, null=True, verbose_name="Event condition")),
                (
                    "agent",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="agent.agent"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_event_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_event_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Intent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("displayName", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True, null=True, verbose_name="Intent description")),
                (
                    "agent",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="agent.agent"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_intent_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_intent_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Intent",
                "verbose_name_plural": "Intents",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="IntentEventAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("displayName", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True, null=True, verbose_name="Event Action description")),
                (
                    "response_type",
                    models.IntegerField(
                        choices=[(1, "TEXT"), (2, "ACTION"), (3, "API")],
                        default=intent.utils.EventActionTypesChoices["TEXT"],
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="agent.agent"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_eventAction_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Intent Event Action",
                "verbose_name_plural": "Intent Event Actions",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ResponseText",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("response_text", models.TextField(blank=True, null=True, verbose_name="Intent response")),
                (
                    "agent",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="agent.agent"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intent_responseText_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intent_event_action",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="intent.intenteventaction"
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intent_responseText_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Intent Response Text",
                "verbose_name_plural": "Intent Response Texts",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="IntentResponseEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("response_text", models.TextField(blank=True, null=True, verbose_name="Intent response")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_intentresponse_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="intent.event"),
                ),
                (
                    "intent",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="intent.intent"),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_intentresponse_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Intent Response Event",
                "verbose_name_plural": "Intent Response Events",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="IntentExample",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("example_text", models.TextField(blank=True, null=True, verbose_name="NLU keywords")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_intentexample_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intent",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="intent.intent"),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_intentexample_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Intent Example",
                "verbose_name_plural": "Intent Examples",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="intenteventaction",
            name="intentResponseEvent",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="intent.intentresponseevent"
            ),
        ),
        migrations.AddField(
            model_name="intenteventaction",
            name="modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_eventAction_modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
