# Generated by Django 4.2.5 on 2023-10-04 23:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("intent", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intentresponseevent",
            name="response_text",
        ),
    ]
