# Generated by Django 4.2.5 on 2023-12-17 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("intent", "0002_remove_intentresponseevent_response_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intentexample",
            name="intent",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="intent", to="intent.intent"
            ),
        ),
    ]
