# Generated by Django 4.2.5 on 2023-09-28 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("body", models.TextField()),
                ("sent_by", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("roomid", models.CharField(blank=True, max_length=255, null=True)),
                ("client", models.CharField(blank=True, max_length=255, null=True)),
                ("url", models.URLField(blank=True, null=True, verbose_name="Website")),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("Waiting", "Waiting"), ("Active", "Active"), ("Closed", "Closed")],
                        default="Waiting",
                        max_length=25,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("messages", models.ManyToManyField(blank=True, to="chat.message")),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
                "ordering": ("-created_at",),
            },
        ),
    ]
