# Generated by Django 4.2.5 on 2023-10-01 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("Waiting", "Waiting"), ("Active", "Active"), ("Closed", "Closed")],
                        default="Waiting",
                        max_length=25,
                        verbose_name="Conversation Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("url", models.URLField(blank=True, null=True, verbose_name="chat session url")),
                ("context_data", models.JSONField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversation_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="message",
            name="context_data",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="message_modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="session_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_by",
            field=models.CharField(
                blank=True,
                choices=[("Human", "Human"), ("AI", "AI"), ("System", "System")],
                default="System",
                max_length=255,
                verbose_name="Sent By",
            ),
        ),
        migrations.DeleteModel(
            name="Room",
        ),
        migrations.AddField(
            model_name="message",
            name="conversationId",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation_id",
                to="chat.conversation",
            ),
        ),
    ]
