# Generated by Django 4.2.5 on 2023-10-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_conversation_message_context_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
