# Generated by Django 4.2.5 on 2023-10-03 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0009_delete_flow"),
        ("chat", "0003_message_modified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="with_agent",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="agent.agent"),
        ),
        migrations.AddField(
            model_name="message",
            name="entity_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="intent",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="agent.intent"),
        ),
    ]
