# Generated by Django 4.2.5 on 2023-10-04 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("intent", "0001_initial"),
        ("chat", "0004_conversation_with_agent_message_entity_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="intent",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="intent.intent"),
        ),
    ]
