# Generated by Django 4.2.5 on 2023-10-04 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("intent", "0002_remove_intentresponseevent_response_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0005_alter_message_intent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="entity_data",
        ),
        migrations.RemoveField(
            model_name="message",
            name="intent",
        ),
        migrations.CreateModel(
            name="MessageFlow",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("entity_data", models.JSONField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messageFlow_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intent",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="intent.intent"),
                ),
                (
                    "message",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="chat.message"),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messageFlow_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Flow",
                "verbose_name_plural": "Message Flow",
                "ordering": ("created_at",),
            },
        ),
    ]
