# Generated by Django 4.2.5 on 2023-12-17 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("intent", "0003_alter_intentexample_intent"),
        ("chat", "0006_remove_message_entity_data_remove_message_intent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messageflow",
            name="IntentEventAction",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="intent.intenteventaction"
            ),
        ),
        migrations.AddField(
            model_name="messageflow",
            name="ResponseText",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="intent.responsetext"),
        ),
        migrations.AddField(
            model_name="messageflow",
            name="intentResponseEvent",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="intent.intentresponseevent"
            ),
        ),
    ]
