# Generated by Django 4.2.5 on 2023-10-02 20:51

import agent.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agent", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityTypes",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("displayName", models.CharField(max_length=500, unique=True)),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "SYSTEM"), (2, "CUSTOM"), (3, "USER"), (0, "DEFAULT")],
                        default=agent.utils.EntityTypesChoices["DEFAULT"],
                    ),
                ),
                ("entities", models.JSONField(null=True)),
                ("excludeList", models.JSONField(null=True)),
                ("description", models.TextField(blank=True, null=True, verbose_name="Entity Type description")),
                ("langCode", models.CharField(max_length=255, unique=True)),
                ("agent", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="agent.agent")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_entity_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity Types",
                "verbose_name_plural": "Entity Types",
                "ordering": ("-created_at",),
            },
        ),
    ]
