# Generated by Django 4.2.5 on 2023-10-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0002_entitytypes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entitytypes",
            name="langCode",
            field=models.CharField(max_length=255),
        ),
    ]
