# Generated by Django 4.2.5 on 2023-10-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0003_alter_entitytypes_langcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entitytypes",
            name="entities",
            field=models.TextField(blank=True, null=True, verbose_name="list of entities"),
        ),
        migrations.AlterField(
            model_name="entitytypes",
            name="excludeList",
            field=models.TextField(blank=True, null=True, verbose_name="list to exclude"),
        ),
    ]
