# Generated by Django 4.2.5 on 2023-10-02 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agent", "0004_alter_entitytypes_entities_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("displayName", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True, null=True, verbose_name="Event description")),
                ("condition", models.TextField(blank=True, null=True, verbose_name="Event condition")),
                (
                    "agent",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="agent.agent"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_event_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_event_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Flow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("displayName", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True, null=True, verbose_name="Flow description")),
                ("randomText", models.TextField(blank=True, null=True, verbose_name="Random texts")),
                ("agent", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="agent.agent")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_flow_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_flow_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Flow",
                "verbose_name_plural": "Flows",
                "ordering": ("-created_at",),
            },
        ),
        migrations.RemoveField(
            model_name="entitytypes",
            name="entities",
        ),
        migrations.RemoveField(
            model_name="entitytypes",
            name="excludeList",
        ),
        migrations.RemoveField(
            model_name="entitytypes",
            name="langCode",
        ),
        migrations.AddField(
            model_name="entitytypes",
            name="modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_entityType_modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="entitytypes",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_entityType_added_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Intent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("displayName", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True, null=True, verbose_name="Intent description")),
                ("nluKeyWords", models.TextField(blank=True, null=True, verbose_name="nlu keywords")),
                (
                    "agent",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="agent.agent"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_intent_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_intent_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Intent",
                "verbose_name_plural": "Intents",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="FlowType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("displayName", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True, null=True, verbose_name="Flow  Type description")),
                (
                    "agent",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="agent.agent"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_flowType_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_flowType_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Flow Type",
                "verbose_name_plural": "Flow Types",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="FlowTransition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("displayName", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True, null=True, verbose_name="Intent description")),
                (
                    "agent",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="agent.agent"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_transitionFlow_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_event",
                        to="agent.event",
                    ),
                ),
                (
                    "flow",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_flow",
                        to="agent.flow",
                    ),
                ),
                (
                    "intent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_intent",
                        to="agent.intent",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_transitionFlow_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Flow Transition",
                "verbose_name_plural": "Flow Transitions",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="flow",
            name="type",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="agent.flowtype"),
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("displayName", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True, null=True, verbose_name="Entity Type description")),
                ("synonyms", models.TextField(blank=True, null=True, verbose_name="Entity synonyms")),
                ("exclude", models.BooleanField(default=False)),
                ("agent", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="agent.agent")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_entity_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_entity_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("type", models.ManyToManyField(related_name="entity_type", to="agent.entitytypes")),
            ],
            options={
                "verbose_name": "Entity",
                "verbose_name_plural": "Entities",
                "ordering": ("-created_at",),
            },
        ),
    ]
