# Generated by Django 4.2.5 on 2023-10-03 21:43

import agent.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_conversation_message_context_data_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agent", "0005_event_flow_remove_entitytypes_entities_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("displayName", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True, null=True, verbose_name="Event Action description")),
                (
                    "response_type",
                    models.IntegerField(
                        choices=[(1, "TEXT"), (2, "ACTION"), (3, "API")],
                        default=agent.utils.EventActionTypesChoices["TEXT"],
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="IntentExample",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("example_text", models.TextField(blank=True, null=True, verbose_name="NLU keywords")),
            ],
            options={
                "verbose_name": "Intent Example",
                "verbose_name_plural": "Intent Examples",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="IntentResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("response_text", models.TextField(blank=True, null=True, verbose_name="Intent response")),
            ],
            options={
                "verbose_name": "Intent Example",
                "verbose_name_plural": "Intent Examples",
                "ordering": ("-created_at",),
            },
        ),
        migrations.RenameField(
            model_name="event",
            old_name="condition",
            new_name="trigger_condition",
        ),
        migrations.RemoveField(
            model_name="flow",
            name="description",
        ),
        migrations.RemoveField(
            model_name="flow",
            name="displayName",
        ),
        migrations.RemoveField(
            model_name="flow",
            name="name",
        ),
        migrations.RemoveField(
            model_name="flow",
            name="randomText",
        ),
        migrations.RemoveField(
            model_name="flow",
            name="type",
        ),
        migrations.RemoveField(
            model_name="intent",
            name="nluKeyWords",
        ),
        migrations.AddField(
            model_name="agent",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="entitytypes",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="flow",
            name="entity_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flow",
            name="intent",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="agent.intent"),
        ),
        migrations.AddField(
            model_name="flow",
            name="message",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="chat.message"),
        ),
        migrations.AddField(
            model_name="flow",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="flowtype",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="intent",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name="FlowTransition",
        ),
        migrations.AddField(
            model_name="intentresponse",
            name="agent",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="agent.agent"),
        ),
        migrations.AddField(
            model_name="intentresponse",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_intentresponse_added_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="intentresponse",
            name="event",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="agent.event"),
        ),
        migrations.AddField(
            model_name="intentresponse",
            name="intent",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="agent.intent"),
        ),
        migrations.AddField(
            model_name="intentresponse",
            name="modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_intentresponse_modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="intentexample",
            name="agent",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="agent.agent"),
        ),
        migrations.AddField(
            model_name="intentexample",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_intentexample_added_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="intentexample",
            name="intent",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="agent.intent"),
        ),
        migrations.AddField(
            model_name="intentexample",
            name="modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_intentexample_modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventaction",
            name="agent",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="agent.agent"),
        ),
        migrations.AddField(
            model_name="eventaction",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_eventAction_added_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventaction",
            name="event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_eventAction_modified_by",
                to="agent.event",
            ),
        ),
        migrations.AddField(
            model_name="eventaction",
            name="modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_eventAction_modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
