# Generated by Django 4.2.5 on 2023-10-03 21:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0006_eventaction_intentexample_intentresponse_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="intentresponse",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Intent Response",
                "verbose_name_plural": "Intent Responses",
            },
        ),
        migrations.DeleteModel(
            name="FlowType",
        ),
    ]
