# Generated by Django 4.2.5 on 2023-10-03 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agent", "0007_alter_intentresponse_options_delete_flowtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
