# Generated by Django 4.2.5 on 2023-10-03 22:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0008_agent_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Flow",
        ),
    ]
