# Generated by Django 4.2.5 on 2023-10-03 22:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0009_delete_flow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intentexample",
            name="agent",
        ),
        migrations.RemoveField(
            model_name="intentresponse",
            name="agent",
        ),
    ]
