# Generated by Django 4.2.5 on 2023-10-04 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agent", "0010_remove_intentexample_agent_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IntentResponse",
            new_name="IntentResponseEvent",
        ),
        migrations.AlterModelOptions(
            name="eventaction",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Event Action",
                "verbose_name_plural": "Event Actions",
            },
        ),
        migrations.AlterModelOptions(
            name="intentresponseevent",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Intent Response Event",
                "verbose_name_plural": "Intent Response Events",
            },
        ),
        migrations.CreateModel(
            name="ResponseText",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("response_text", models.TextField(blank=True, null=True, verbose_name="Intent response")),
                (
                    "agent",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="agent.agent"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intent_responseText_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eventAction",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="agent.eventaction"),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intent_responseText_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Intent Response Text",
                "verbose_name_plural": "Intent Response Texts",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ResponseAPI",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("response_API_URL", models.URLField(blank=True, null=True, verbose_name="Intent response API URL")),
                (
                    "agent",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="agent.agent"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intent_responseAPI_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eventAction",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="agent.eventaction"),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intent_responseAPI_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Intent API Action",
                "verbose_name_plural": "Intent API Actions",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ResponseAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "response_action",
                    models.TextField(blank=True, null=True, verbose_name="Intent response action html"),
                ),
                (
                    "agent",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="agent.agent"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intent_responseAction_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eventAction",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="agent.eventaction"),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intent_responseAction_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Intent Action",
                "verbose_name_plural": "Intent Actions",
                "ordering": ("-created_at",),
            },
        ),
    ]
