# Generated by Django 4.2.5 on 2023-10-04 21:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agent", "0012_remove_eventaction_event_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EventAction",
            new_name="IntentEventAction",
        ),
        migrations.RemoveField(
            model_name="responseapi",
            name="agent",
        ),
        migrations.RemoveField(
            model_name="responseapi",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="responseapi",
            name="eventAction",
        ),
        migrations.RemoveField(
            model_name="responseapi",
            name="modified_by",
        ),
        migrations.RenameField(
            model_name="responsetext",
            old_name="eventAction",
            new_name="intent_event_action",
        ),
        migrations.DeleteModel(
            name="ResponseAction",
        ),
        migrations.DeleteModel(
            name="ResponseAPI",
        ),
    ]
