# Generated by Django 4.2.5 on 2023-10-04 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import entity.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agent", "0014_remove_entitytypes_agent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityTypes",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("displayName", models.CharField(max_length=500, unique=True)),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "SYSTEM"), (2, "CUSTOM"), (3, "USER"), (0, "DEFAULT")],
                        default=entity.utils.EntityTypesChoices["DEFAULT"],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="Entity Type description")),
                ("agent", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="agent.agent")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_entityType_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_entityType_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity Types",
                "verbose_name_plural": "Entity Types",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("displayName", models.CharField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True, null=True, verbose_name="Entity Type description")),
                ("synonyms", models.TextField(blank=True, null=True, verbose_name="Entity synonyms")),
                ("exclude", models.BooleanField(default=False)),
                ("agent", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="agent.agent")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_entity_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_entity_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("type", models.ManyToManyField(related_name="entity_type", to="entity.entitytypes")),
            ],
            options={
                "verbose_name": "Entity",
                "verbose_name_plural": "Entities",
                "ordering": ("-created_at",),
            },
        ),
    ]
